//ProductsInfo.jsx


const infoproducts = [
  // ================= BRAS =================
  {
    id: 1,
    category: "BRAS",
    subCategory: "T-Shirt Bras",
    name: "Everyday Comfort T-Shirt Bra",
    images: [
      "https://picsum.photos/400/400?random=1",
      "https://picsum.photos/400/400?random=2",
      "https://picsum.photos/400/400?random=3",
      "https://picsum.photos/400/400?random=4",
    ],
    price: 799,
    originalPrice: 1299,
    description: "Soft padded T-shirt bra designed for daily comfort with seamless fit.",
    colors: ["Black", "Nude", "Pink", "White"],
    sizes: ["32B", "34B", "36B", "34C", "36C", "38C"],
  },
  {
    id: 2,
    category: "BRAS",
    subCategory: "Sports Bras",
    name: "High Support Sports Bra",
    images: [
      "https://picsum.photos/400/400?random=5",
      "https://picsum.photos/400/400?random=6",
      "https://picsum.photos/400/400?random=7",
      "https://picsum.photos/400/400?random=8",
    ],
    price: 999,
    originalPrice: 1499,
    description: "Breathable sports bra with high support for workouts and running.",
    colors: ["Black", "Grey", "Blue", "Red"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 3,
    category: "BRAS",
    subCategory: "Push-Up Bras",
    name: "Classic Push-Up Bra",
    images: [
      "https://picsum.photos/400/400?random=9",
      "https://picsum.photos/400/400?random=10",
      "https://picsum.photos/400/400?random=11",
      "https://picsum.photos/400/400?random=12",
    ],
    price: 899,
    originalPrice: 1399,
    description: "Enhance your shape with this classic push-up bra featuring lace detailing.",
    colors: ["Red", "Black", "Beige"],
    sizes: ["32A", "34B", "36B", "34C", "36C"],
  },
  {
    id: 4,
    category: "BRAS",
    subCategory: "T-Shirt Bras",
    name: "Everyday Comfort T-Shirt Bra",
    images: [
      "https://picsum.photos/400/400?random=1",
      "https://picsum.photos/400/400?random=2",
      "https://picsum.photos/400/400?random=3",
      "https://picsum.photos/400/400?random=4",
    ],
    price: 799,
    originalPrice: 1299,
    description: "Soft padded T-shirt bra designed for daily comfort with seamless fit.",
    colors: ["Black", "Nude", "Pink", "White"],
    sizes: ["32B", "34B", "36B", "34C", "36C", "38C"],
  },
  {
    id: 5,
    category: "BRAS",
    subCategory: "Sports Bras",
    name: "High Support Sports Bra",
    images: [
      "https://picsum.photos/400/400?random=5",
      "https://picsum.photos/400/400?random=6",
      "https://picsum.photos/400/400?random=7",
      "https://picsum.photos/400/400?random=8",
    ],
    price: 999,
    originalPrice: 1499,
    description: "Breathable sports bra with high support for workouts and running.",
    colors: ["Black", "Grey", "Blue", "Red"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 6,
    category: "BRAS",
    subCategory: "Push-Up Bras",
    name: "Classic Push-Up Bra",
    images: [
      "https://picsum.photos/400/400?random=9",
      "https://picsum.photos/400/400?random=10",
      "https://picsum.photos/400/400?random=11",
      "https://picsum.photos/400/400?random=12",
    ],
    price: 899,
    originalPrice: 1399,
    description: "Enhance your shape with this classic push-up bra featuring lace detailing.",
    colors: ["Red", "Black", "Beige"],
    sizes: ["32A", "34B", "36B", "34C", "36C"],
  },{
    id: 7,
    category: "BRAS",
    subCategory: "T-Shirt Bras",
    name: "Everyday Comfort T-Shirt Bra",
    images: [
      "https://picsum.photos/400/400?random=1",
      "https://picsum.photos/400/400?random=2",
      "https://picsum.photos/400/400?random=3",
      "https://picsum.photos/400/400?random=4",
    ],
    price: 799,
    originalPrice: 1299,
    description: "Soft padded T-shirt bra designed for daily comfort with seamless fit.",
    colors: ["Black", "Nude", "Pink", "White"],
    sizes: ["32B", "34B", "36B", "34C", "36C", "38C"],
  },
  {
    id: 8,
    category: "BRAS",
    subCategory: "Sports Bras",
    name: "High Support Sports Bra",
    images: [
      "https://picsum.photos/400/400?random=5",
      "https://picsum.photos/400/400?random=6",
      "https://picsum.photos/400/400?random=7",
      "https://picsum.photos/400/400?random=8",
    ],
    price: 999,
    originalPrice: 1499,
    description: "Breathable sports bra with high support for workouts and running.",
    colors: ["Black", "Grey", "Blue", "Red"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 9,
    category: "BRAS",
    subCategory: "Push-Up Bras",
    name: "Classic Push-Up Bra",
    images: [
      "https://picsum.photos/400/400?random=9",
      "https://picsum.photos/400/400?random=10",
      "https://picsum.photos/400/400?random=11",
      "https://picsum.photos/400/400?random=12",
    ],
    price: 899,
    originalPrice: 1399,
    description: "Enhance your shape with this classic push-up bra featuring lace detailing.",
    colors: ["Red", "Black", "Beige"],
    sizes: ["32A", "34B", "36B", "34C", "36C"],
  },{
    id: 10,
    category: "BRAS",
    subCategory: "T-Shirt Bras",
    name: "Everyday Comfort T-Shirt Bra",
    images: [
      "https://picsum.photos/400/400?random=1",
      "https://picsum.photos/400/400?random=2",
      "https://picsum.photos/400/400?random=3",
      "https://picsum.photos/400/400?random=4",
    ],
    price: 799,
    originalPrice: 1299,
    description: "Soft padded T-shirt bra designed for daily comfort with seamless fit.",
    colors: ["Black", "Nude", "Pink", "White"],
    sizes: ["32B", "34B", "36B", "34C", "36C", "38C"],
  },
  {
    id: 11,
    category: "BRAS",
    subCategory: "Sports Bras",
    name: "High Support Sports Bra",
    images: [
      "https://picsum.photos/400/400?random=5",
      "https://picsum.photos/400/400?random=6",
      "https://picsum.photos/400/400?random=7",
      "https://picsum.photos/400/400?random=8",
    ],
    price: 999,
    originalPrice: 1499,
    description: "Breathable sports bra with high support for workouts and running.",
    colors: ["Black", "Grey", "Blue", "Red"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 12,
    category: "BRAS",
    subCategory: "Push-Up Bras",
    name: "Classic Push-Up Bra",
    images: [
      "https://picsum.photos/400/400?random=9",
      "https://picsum.photos/400/400?random=10",
      "https://picsum.photos/400/400?random=11",
      "https://picsum.photos/400/400?random=12",
    ],
    price: 899,
    originalPrice: 1399,
    description: "Enhance your shape with this classic push-up bra featuring lace detailing.",
    colors: ["Red", "Black", "Beige"],
    sizes: ["32A", "34B", "36B", "34C", "36C"],
  },
  {
    id: 13,
    category: "BRAS",
    subCategory: "T-Shirt Bras",
    name: "Everyday Comfort T-Shirt Bra",
    images: [
      "https://picsum.photos/400/400?random=1",
      "https://picsum.photos/400/400?random=2",
      "https://picsum.photos/400/400?random=3",
      "https://picsum.photos/400/400?random=4",
    ],
    price: 799,
    originalPrice: 1299,
    description: "Soft padded T-shirt bra designed for daily comfort with seamless fit.",
    colors: ["Black", "Nude", "Pink", "White"],
    sizes: ["32B", "34B", "36B", "34C", "36C", "38C"],
  },
  {
    id: 14,
    category: "BRAS",
    subCategory: "Sports Bras",
    name: "High Support Sports Bra",
    images: [
      "https://picsum.photos/400/400?random=5",
      "https://picsum.photos/400/400?random=6",
      "https://picsum.photos/400/400?random=7",
      "https://picsum.photos/400/400?random=8",
    ],
    price: 999,
    originalPrice: 1499,
    description: "Breathable sports bra with high support for workouts and running.",
    colors: ["Black", "Grey", "Blue", "Red"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 15,
    category: "BRAS",
    subCategory: "Push-Up Bras",
    name: "Classic Push-Up Bra",
    images: [
      "https://picsum.photos/400/400?random=9",
      "https://picsum.photos/400/400?random=10",
      "https://picsum.photos/400/400?random=11",
      "https://picsum.photos/400/400?random=12",
    ],
    price: 899,
    originalPrice: 1399,
    description: "Enhance your shape with this classic push-up bra featuring lace detailing.",
    colors: ["Red", "Black", "Beige"],
    sizes: ["32A", "34B", "36B", "34C", "36C"],
  },{
    id: 16,
    category: "BRAS",
    subCategory: "T-Shirt Bras",
    name: "Everyday Comfort T-Shirt Bra",
    images: [
      "https://picsum.photos/400/400?random=1",
      "https://picsum.photos/400/400?random=2",
      "https://picsum.photos/400/400?random=3",
      "https://picsum.photos/400/400?random=4",
    ],
    price: 799,
    originalPrice: 1299,
    description: "Soft padded T-shirt bra designed for daily comfort with seamless fit.",
    colors: ["Black", "Nude", "Pink", "White"],
    sizes: ["32B", "34B", "36B", "34C", "36C", "38C"],
  },
  {
    id: 17,
    category: "BRAS",
    subCategory: "Sports Bras",
    name: "High Support Sports Bra",
    images: [
      "https://picsum.photos/400/400?random=5",
      "https://picsum.photos/400/400?random=6",
      "https://picsum.photos/400/400?random=7",
      "https://picsum.photos/400/400?random=8",
    ],
    price: 999,
    originalPrice: 1499,
    description: "Breathable sports bra with high support for workouts and running.",
    colors: ["Black", "Grey", "Blue", "Red"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 18,
    category: "BRAS",
    subCategory: "Push-Up Bras",
    name: "Classic Push-Up Bra",
    images: [
      "https://picsum.photos/400/400?random=9",
      "https://picsum.photos/400/400?random=10",
      "https://picsum.photos/400/400?random=11",
      "https://picsum.photos/400/400?random=12",
    ],
    price: 899,
    originalPrice: 1399,
    description: "Enhance your shape with this classic push-up bra featuring lace detailing.",
    colors: ["Red", "Black", "Beige"],
    sizes: ["32A", "34B", "36B", "34C", "36C"],
  },
  {
    id: 19,
    category: "BRAS",
    subCategory: "Push-Up Bras",
    name: "Classic Push-Up Bra",
    images: [
      "https://picsum.photos/400/400?random=9",
      "https://picsum.photos/400/400?random=10",
      "https://picsum.photos/400/400?random=11",
      "https://picsum.photos/400/400?random=12",
    ],
    price: 899,
    originalPrice: 1399,
    description: "Enhance your shape with this classic push-up bra featuring lace detailing.",
    colors: ["Red", "Black", "Beige"],
    sizes: ["32A", "34B", "36B", "34C", "36C"],
  },
  

  // ================= PANTIES =================
  {
    id: 20,
    category: "PANTIES",
    subCategory: "Bikini",
    name: "Cotton Bikini Panties (Pack of 3)",
    images: [
      "https://picsum.photos/400/400?random=21",
      "https://picsum.photos/400/400?random=22",
      "https://picsum.photos/400/400?random=23",
      "https://picsum.photos/400/400?random=24",
    ],
    price: 499,
    originalPrice: 899,
    description: "Breathable cotton bikini panties designed for all-day comfort.",
    colors: ["Black", "White", "Red"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 21,
    category: "PANTIES",
    subCategory: "Boyshorts",
    name: "Seamless Boyshort Panties",
    images: [
      "https://picsum.photos/400/400?random=25",
      "https://picsum.photos/400/400?random=26",
      "https://picsum.photos/400/400?random=27",
      "https://picsum.photos/400/400?random=28",
    ],
    price: 399,
    originalPrice: 699,
    description: "Comfortable boyshort panties with a smooth finish.",
    colors: ["Grey", "Navy", "Peach"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 22,
    category: "PANTIES",
    subCategory: "Bikini",
    name: "Cotton Bikini Panties (Pack of 3)",
    images: [
      "https://picsum.photos/400/400?random=21",
      "https://picsum.photos/400/400?random=22",
      "https://picsum.photos/400/400?random=23",
      "https://picsum.photos/400/400?random=24",
    ],
    price: 499,
    originalPrice: 899,
    description: "Breathable cotton bikini panties designed for all-day comfort.",
    colors: ["Black", "White", "Red"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 23,
    category: "PANTIES",
    subCategory: "Boyshorts",
    name: "Seamless Boyshort Panties",
    images: [
      "https://picsum.photos/400/400?random=25",
      "https://picsum.photos/400/400?random=26",
      "https://picsum.photos/400/400?random=27",
      "https://picsum.photos/400/400?random=28",
    ],
    price: 399,
    originalPrice: 699,
    description: "Comfortable boyshort panties with a smooth finish.",
    colors: ["Grey", "Navy", "Peach"],
    sizes: ["S", "M", "L", "XL"],
  },{
    id: 24,
    category: "PANTIES",
    subCategory: "Bikini",
    name: "Cotton Bikini Panties (Pack of 3)",
    images: [
      "https://picsum.photos/400/400?random=21",
      "https://picsum.photos/400/400?random=22",
      "https://picsum.photos/400/400?random=23",
      "https://picsum.photos/400/400?random=24",
    ],
    price: 499,
    originalPrice: 899,
    description: "Breathable cotton bikini panties designed for all-day comfort.",
    colors: ["Black", "White", "Red"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 25,
    category: "PANTIES",
    subCategory: "Boyshorts",
    name: "Seamless Boyshort Panties",
    images: [
      "https://picsum.photos/400/400?random=25",
      "https://picsum.photos/400/400?random=26",
      "https://picsum.photos/400/400?random=27",
      "https://picsum.photos/400/400?random=28",
    ],
    price: 399,
    originalPrice: 699,
    description: "Comfortable boyshort panties with a smooth finish.",
    colors: ["Grey", "Navy", "Peach"],
    sizes: ["S", "M", "L", "XL"],
  },{
    id: 26,
    category: "PANTIES",
    subCategory: "Bikini",
    name: "Cotton Bikini Panties (Pack of 3)",
    images: [
      "https://picsum.photos/400/400?random=21",
      "https://picsum.photos/400/400?random=22",
      "https://picsum.photos/400/400?random=23",
      "https://picsum.photos/400/400?random=24",
    ],
    price: 499,
    originalPrice: 899,
    description: "Breathable cotton bikini panties designed for all-day comfort.",
    colors: ["Black", "White", "Red"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 27,
    category: "PANTIES",
    subCategory: "Boyshorts",
    name: "Seamless Boyshort Panties",
    images: [
      "https://picsum.photos/400/400?random=25",
      "https://picsum.photos/400/400?random=26",
      "https://picsum.photos/400/400?random=27",
      "https://picsum.photos/400/400?random=28",
    ],
    price: 399,
    originalPrice: 699,
    description: "Comfortable boyshort panties with a smooth finish.",
    colors: ["Grey", "Navy", "Peach"],
    sizes: ["S", "M", "L", "XL"],
  },{
    id: 28,
    category: "PANTIES",
    subCategory: "Bikini",
    name: "Cotton Bikini Panties (Pack of 3)",
    images: [
      "https://picsum.photos/400/400?random=21",
      "https://picsum.photos/400/400?random=22",
      "https://picsum.photos/400/400?random=23",
      "https://picsum.photos/400/400?random=24",
    ],
    price: 499,
    originalPrice: 899,
    description: "Breathable cotton bikini panties designed for all-day comfort.",
    colors: ["Black", "White", "Red"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 29,
    category: "PANTIES",
    subCategory: "Boyshorts",
    name: "Seamless Boyshort Panties",
    images: [
      "https://picsum.photos/400/400?random=25",
      "https://picsum.photos/400/400?random=26",
      "https://picsum.photos/400/400?random=27",
      "https://picsum.photos/400/400?random=28",
    ],
    price: 399,
    originalPrice: 699,
    description: "Comfortable boyshort panties with a smooth finish.",
    colors: ["Grey", "Navy", "Peach"],
    sizes: ["S", "M", "L", "XL"],
  },{
    id: 30,
    category: "PANTIES",
    subCategory: "Bikini",
    name: "Cotton Bikini Panties (Pack of 3)",
    images: [
      "https://picsum.photos/400/400?random=21",
      "https://picsum.photos/400/400?random=22",
      "https://picsum.photos/400/400?random=23",
      "https://picsum.photos/400/400?random=24",
    ],
    price: 499,
    originalPrice: 899,
    description: "Breathable cotton bikini panties designed for all-day comfort.",
    colors: ["Black", "White", "Red"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 31,
    category: "PANTIES",
    subCategory: "Boyshorts",
    name: "Seamless Boyshort Panties",
    images: [
      "https://picsum.photos/400/400?random=25",
      "https://picsum.photos/400/400?random=26",
      "https://picsum.photos/400/400?random=27",
      "https://picsum.photos/400/400?random=28",
    ],
    price: 399,
    originalPrice: 699,
    description: "Comfortable boyshort panties with a smooth finish.",
    colors: ["Grey", "Navy", "Peach"],
    sizes: ["S", "M", "L", "XL"],
  },{
    id: 32,
    category: "PANTIES",
    subCategory: "Bikini",
    name: "Cotton Bikini Panties (Pack of 3)",
    images: [
      "https://picsum.photos/400/400?random=21",
      "https://picsum.photos/400/400?random=22",
      "https://picsum.photos/400/400?random=23",
      "https://picsum.photos/400/400?random=24",
    ],
    price: 499,
    originalPrice: 899,
    description: "Breathable cotton bikini panties designed for all-day comfort.",
    colors: ["Black", "White", "Red"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 33,
    category: "PANTIES",
    subCategory: "Boyshorts",
    name: "Seamless Boyshort Panties",
    images: [
      "https://picsum.photos/400/400?random=25",
      "https://picsum.photos/400/400?random=26",
      "https://picsum.photos/400/400?random=27",
      "https://picsum.photos/400/400?random=28",
    ],
    price: 399,
    originalPrice: 699,
    description: "Comfortable boyshort panties with a smooth finish.",
    colors: ["Grey", "Navy", "Peach"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 34,
    category: "PANTIES",
    subCategory: "Boyshorts",
    name: "Seamless Boyshort Panties",
    images: [
      "https://picsum.photos/400/400?random=25",
      "https://picsum.photos/400/400?random=26",
      "https://picsum.photos/400/400?random=27",
      "https://picsum.photos/400/400?random=28",
    ],
    price: 399,
    originalPrice: 699,
    description: "Comfortable boyshort panties with a smooth finish.",
    colors: ["Grey", "Navy", "Peach"],
    sizes: ["S", "M", "L", "XL"],
  },{
    id: 35,
    category: "PANTIES",
    subCategory: "Bikini",
    name: "Cotton Bikini Panties (Pack of 3)",
    images: [
      "https://picsum.photos/400/400?random=21",
      "https://picsum.photos/400/400?random=22",
      "https://picsum.photos/400/400?random=23",
      "https://picsum.photos/400/400?random=24",
    ],
    price: 499,
    originalPrice: 899,
    description: "Breathable cotton bikini panties designed for all-day comfort.",
    colors: ["Black", "White", "Red"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 36,
    category: "PANTIES",
    subCategory: "Boyshorts",
    name: "Seamless Boyshort Panties",
    images: [
      "https://picsum.photos/400/400?random=25",
      "https://picsum.photos/400/400?random=26",
      "https://picsum.photos/400/400?random=27",
      "https://picsum.photos/400/400?random=28",
    ],
    price: 399,
    originalPrice: 699,
    description: "Comfortable boyshort panties with a smooth finish.",
    colors: ["Grey", "Navy", "Peach"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 37,
    category: "PANTIES",
    subCategory: "Bikini",
    name: "Cotton Bikini Panties (Pack of 3)",
    images: [
      "https://picsum.photos/400/400?random=21",
      "https://picsum.photos/400/400?random=22",
      "https://picsum.photos/400/400?random=23",
      "https://picsum.photos/400/400?random=24",
    ],
    price: 499,
    originalPrice: 899,
    description: "Breathable cotton bikini panties designed for all-day comfort.",
    colors: ["Black", "White", "Red"],
    sizes: ["S", "M", "L", "XL"],
  },{
    id: 38,
    category: "PANTIES",
    subCategory: "Bikini",
    name: "Cotton Bikini Panties (Pack of 3)",
    images: [
      "https://picsum.photos/400/400?random=21",
      "https://picsum.photos/400/400?random=22",
      "https://picsum.photos/400/400?random=23",
      "https://picsum.photos/400/400?random=24",
    ],
    price: 499,
    originalPrice: 899,
    description: "Breathable cotton bikini panties designed for all-day comfort.",
    colors: ["Black", "White", "Red"],
    sizes: ["S", "M", "L", "XL"],
  },{
    id: 39,
    category: "PANTIES",
    subCategory: "Bikini",
    name: "Cotton Bikini Panties (Pack of 3)",
    images: [
      "https://picsum.photos/400/400?random=21",
      "https://picsum.photos/400/400?random=22",
      "https://picsum.photos/400/400?random=23",
      "https://picsum.photos/400/400?random=24",
    ],
    price: 499,
    originalPrice: 899,
    description: "Breathable cotton bikini panties designed for all-day comfort.",
    colors: ["Black", "White", "Red"],
    sizes: ["S", "M", "L", "XL"],
  },
  // ... Continue Panties up to id: 39

  // ================= LINGERIE =================
  {
    id: 40,
    category: "LINGERIE",
    subCategory: "Nightwear",
    name: "Silk Nightdress",
    images: [
      "https://picsum.photos/400/400?random=41",
      "https://picsum.photos/400/400?random=42",
      "https://picsum.photos/400/400?random=43",
      "https://picsum.photos/400/400?random=44",
    ],
    price: 1299,
    originalPrice: 1999,
    description: "Elegant silk nightdress for a luxurious sleep experience.",
    colors: ["Red", "Navy Blue", "Pink"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: 41,
    category: "LINGERIE",
    subCategory: "Babydolls",
    name: "Lace Babydoll Set",
    images: [
      "https://picsum.photos/400/400?random=45",
      "https://picsum.photos/400/400?random=46",
      "https://picsum.photos/400/400?random=47",
      "https://picsum.photos/400/400?random=48",
    ],
    price: 1499,
    originalPrice: 2499,
    description: "Romantic lace babydoll set with matching thong.",
    colors: ["Black", "Wine Red"],
    sizes: ["S", "M", "L"],
  },
  // ... Continue LINGERIE up to id: 59

  // ================= APPAREL =================
  {
    id: 60,
    category: "APPAREL",
    subCategory: "Tops",
    name: "Casual Cotton Top",
    images: [
      "https://picsum.photos/400/400?random=61",
      "https://picsum.photos/400/400?random=62",
      "https://picsum.photos/400/400?random=63",
      "https://picsum.photos/400/400?random=64",
    ],
    price: 699,
    originalPrice: 1099,
    description: "Breathable cotton top perfect for everyday wear.",
    colors: ["White", "Black", "Yellow", "Blue"],
    sizes: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: 61,
    category: "APPAREL",
    subCategory: "Dresses",
    name: "Floral Summer Dress",
    images: [
      "https://picsum.photos/400/400?random=65",
      "https://picsum.photos/400/400?random=66",
      "https://picsum.photos/400/400?random=67",
      "https://picsum.photos/400/400?random=68",
    ],
    price: 1499,
    originalPrice: 2299,
    description: "Lightweight floral dress designed for comfort and style.",
    colors: ["Yellow", "Blue", "Pink"],
    sizes: ["S", "M", "L", "XL"],
  },
  // ... Continue Apparel up to id: 79

  // ================= BEAUTY =================
  {
    id: 80,
    category: "BEAUTY",
    subCategory: "Skincare",
    name: "Aloe Vera Face Cream",
    images: [
      "https://picsum.photos/400/400?random=81",
      "https://picsum.photos/400/400?random=82",
      "https://picsum.photos/400/400?random=83",
      "https://picsum.photos/400/400?random=84",
    ],
    price: 349,
    originalPrice: 599,
    description: "Hydrating aloe vera cream for fresh and glowing skin.",
    colors: ["Green"],
    sizes: ["100ml", "200ml"],
  },
  {
    id: 81,
    category: "BEAUTY",
    subCategory: "Makeup",
    name: "Matte Lipstick Set",
    images: [
      "https://picsum.photos/400/400?random=85",
      "https://picsum.photos/400/400?random=86",
      "https://picsum.photos/400/400?random=87",
      "https://picsum.photos/400/400?random=88",
    ],
    price: 499,
    originalPrice: 999,
    description: "Pack of 3 matte lipsticks with long-lasting color.",
    colors: ["Red", "Nude", "Rose"],
    sizes: ["3 Shades"],
  },
  // ... Continue Beauty up to id: 99

  // ================= CLEARANCE =================
  {
    id: 100,
    category: "CLEARANCE",
    subCategory: "Last Chance",
    name: "Lace Bra - Clearance",
    images: [
      "https://picsum.photos/400/400?random=101",
      "https://picsum.photos/400/400?random=102",
      "https://picsum.photos/400/400?random=103",
      "https://picsum.photos/400/400?random=104",
    ],
    price: 399,
    originalPrice: 1299,
    description: "Beautiful lace bra available at clearance price.",
    colors: ["Red", "Black"],
    sizes: ["32B", "34B", "36B"],
  },
  {
    id: 101,
    category: "CLEARANCE",
    subCategory: "Panty Sets",
    name: "Printed Panty Set - Clearance",
    images: [
      "https://picsum.photos/400/400?random=105",
      "https://picsum.photos/400/400?random=106",
      "https://picsum.photos/400/400?random=107",
      "https://picsum.photos/400/400?random=108",
    ],
    price: 199,
    originalPrice: 699,
    description: "Printed panty set in clearance with limited stock.",
    colors: ["Multi"],
    sizes: ["S", "M", "L"],
  },
  {
    id: 102,
    category: "BEAUTY",
    subCategory: "Makeup",
    name: "Matte Lipstick Set",
    images: [
      "https://picsum.photos/400/400?random=85",
      "https://picsum.photos/400/400?random=86",
      "https://picsum.photos/400/400?random=87",
      "https://picsum.photos/400/400?random=88",
    ],
    price: 499,
    originalPrice: 999,
    description: "Pack of 3 matte lipsticks with long-lasting color.",
    colors: ["Red", "Nude", "Rose"],
    sizes: ["3 Shades"],
  },
  // ... Continue Clearance up to id: 110
];

export default infoproducts;
